# Generated by Django 6.0.7 on 2026-07-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='ai_match_score',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='matched_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='missing_skills',
            field=models.JSONField(default=list),
        ),
    ]
