# Generated by Django 6.0.7 on 2026-07-18 12:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_jobapplication_ai_match_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 18, 12, 12, 32, 3138, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.jobpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default=1, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='Pending Review', max_length=50),
        ),
    ]
